# Generated by Django 2.2.16 on 2022-08-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(max_length=15, null=True, verbose_name='Код подтверждения'),
        ),
    ]
