# Generated by Django 2.2.16 on 2022-08-15 14:57

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_comment_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveIntegerField(validators=[reviews.models.validate_year], verbose_name='Год выпуска'),
        ),
    ]
