# Generated by Django 2.2.16 on 2022-08-14 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220812_0930'),
        ('reviews', '0003_auto_20220814_1834'),
    ]

    operations = [
    ]
