# Generated by Django 2.2.16 on 2022-10-28 10:49

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20221028_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=256, validators=[reviews.validators.validate_slug]),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=256, validators=[reviews.validators.validate_slug]),
        ),
    ]
